# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '288cc4c8-ea99-4458-8549-b1e593965d27/c799fd2d-5d83-43dc-b53e-5c4902bfb6cd'
    vstsFeedPackagePublish: 'testpackage'
    versionOption: 'patch'
    packagePublishDescription: 'package'
